### ISSUE TITLE
Incorrect inference of multi-index in the case of non-str index

### ISSUE THREAD

**Issue by fwzhao** [afrendeiro/toolkit#59]
https://github.com/afrendeiro/toolkit/blob/1dfa4d0a8b30ccb9e9be57b7663f798a5016ab5e/ngs_toolkit/utils.py#L554-L580

Context:
Upon analysis.load_data() of matrix_norm, inference of multi-index levels excludes non-str levels e.g. boolean entries (in my case, toggle/exclude), and numeric factors (e.g. cell_count), and regardless of whether numeric attributes were designated in annotate_samples.

See below for what I mean by the bug:
In [41]: analysis.matrix_norm.index
Out[41]: 
Index(['exclude', 'toggle', 'cell_count', 'chr1:9843-10840',
       'chr1:15983-16492', 'chr1:180528-181802', 'chr1:191092-192113',
       'chr1:267741-268289', 'chr1:585847-586457', 'chr1:605341-605844',
       ...
       'chrY:56825538-56826039', 'chrY:56836469-56837142',
       'chrY:56841935-56842436', 'chrY:56843501-56844002',
       'chrY:56845972-56846473', 'chrY:56849062-56849563',
       'chrY:56855527-56856028', 'chrY:56870612-56871192',
       'chrY:56873351-56874110', 'chrY:56879337-56879838'],
      dtype='object', length=211111)

**Comment by afrendeiro** [comment]
60b71f6c9df4ab721f9e185a3893c7d6e3ff87aa now assumes the "matrix_norm" key in `Analysis.load_data` to be a non-MultiIndex dataframe.
However, it will check that all columns are of type `float` (as a matrix_norm attribute should) and throw a detailed message on what is the likely cause (MultiIndex CSV) and how to read it in properly manually: `analysis.matrix_norm = pandas.read_csv('{file}', index_col=0, header=list(range(x)))`, `x` being the number of header rows.

Since `Analysis.annotate_samples` now defaults to `save=False` I think this should solve the issue.
